#!/usr/bin/env bash
# GoalDone Dependency Installation Script
# Installs system packages and dependencies requiring sudo
# Call this before deploy.sh

set -euo pipefail
IFS=$'\n\t'

# ==============================================================================
# Global Variables
# ==============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="${SCRIPT_DIR}/.install-deps-state"
CREDS_FILE="${SCRIPT_DIR}/.install-deps-state.creds"
LOG_FILE="${SCRIPT_DIR}/install-deps.log"
TOTAL_STEPS=3
START_STEP=1
LAST_COMPLETED_STEP=0
SCRIPT_START_TIME=$(date +%s)

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Trap variables
CLEANUP_CALLED=false

# Initialize terminal output FD
exec 3>&1

# ==============================================================================
# Helper Functions - Output
# ==============================================================================
get_timestamp() {
    date +"[%H:%M:%S]"
}

get_duration() {
    local start=$1
    local end
    end=$(date +%s)
    local diff=$((end - start))
    printf "%dm %ds" $((diff / 60)) $((diff % 60))
}

show_header() {
    local title=$1
    local width
    width=$(tput cols 2>/dev/null || echo 80)
    local title_len=${#title}
    local padding=$(( (width - title_len - 4) / 2 ))

    echo "" >&3
    if [[ $padding -gt 0 ]]; then
        printf "%${padding}s" "" | tr ' ' '=' >&3
    fi
    printf "  %s  " "$title" >&3
    if [[ $padding -gt 0 ]]; then
        printf "%${padding}s" "" | tr ' ' '=' >&3
    fi
    echo "" >&3
}

show_success() {
    echo -e "$(get_timestamp) ${GREEN}✓ $1${NC}" >&3
}

show_error() {
    echo -e "$(get_timestamp) ${RED}✗ Error: $1${NC}" >&3
}

show_warning() {
    echo -e "$(get_timestamp) ${YELLOW}⚠ Warning: $1${NC}" >&3
}

show_info() {
    echo -e "$(get_timestamp) ${BLUE}⏳ $1${NC}" >&3
}

show_spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'

    # Hide cursor
    tput civis >&3 2>/dev/null || true

    while kill -0 "$pid" 2>/dev/null; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr" >&3
        spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b" >&3
    done

    # Clear spinner and show cursor
    printf "    \b\b\b\b" >&3
    tput cnorm >&3 2>/dev/null || true
}

show_troubleshooting_hint() {
    local service=$1
    echo "" >&3
    echo -e "${YELLOW}💡 Troubleshooting Hint for $service:${NC}" >&3
    case "$service" in
        apt)
            echo "  - Check your internet connection." >&3
            echo "  - Ensure no other package manager is running (check for /var/lib/dpkg/lock-frontend)." >&3
            echo "  - Try running 'sudo apt-get update' manually." >&3
            ;;
        docker)
            echo "  - Check if Docker service is running: 'sudo systemctl status docker'." >&3
            echo "  - Verify installed version: 'docker --version'." >&3
            ;;
        *)
            echo "  - Check the log file for detailed error messages: $LOG_FILE" >&3
            ;;
    esac
    echo "" >&3
}

error_exit() {
    local msg=$1
    local service=${2:-}

    show_error "$msg"
    if [[ -n "$service" ]]; then
        show_troubleshooting_hint "$service"
    fi
    exit 1
}

# ==============================================================================
# Helper Functions - State Management
# ==============================================================================
load_state() {
    if [[ -f "$STATE_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$STATE_FILE"
    else
        LAST_COMPLETED_STEP=0
        ZITADEL_DOMAIN=""
        GOALDONE_URL=""
        TERRAFORM_TOKEN=""
        BACKEND_PAT=""
        APP_CLIENT_ID=""
        DEPLOY_WORK_DIR=""
    fi

    if [[ -f "$CREDS_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$CREDS_FILE" 2>/dev/null || true
    fi
}

save_state() {
    local temp_file="${STATE_FILE}.tmp"

    cat > "$temp_file" <<EOF
# Generated by install-deps.sh at $(date)
LAST_COMPLETED_STEP=$LAST_COMPLETED_STEP
STEP_1_VERIFY_PREREQUISITES=${STEP_1_VERIFY_PREREQUISITES:-pending}
STEP_2_INSTALL_PACKAGES=${STEP_2_INSTALL_PACKAGES:-pending}
STEP_3_CONFIGURE_UFW=${STEP_3_CONFIGURE_UFW:-pending}
ZITADEL_DOMAIN=${ZITADEL_DOMAIN:-}
GOALDONE_URL=${GOALDONE_URL:-}
TERRAFORM_TOKEN=${TERRAFORM_TOKEN:-}
BACKEND_PAT=${BACKEND_PAT:-}
APP_CLIENT_ID=${APP_CLIENT_ID:-}
DEPLOY_WORK_DIR=${DEPLOY_WORK_DIR:-}
EOF

    if mv "$temp_file" "$STATE_FILE"; then
        show_success "State saved."
    else
        show_error "Failed to save state."
        rm -f "$temp_file"
        return 1
    fi
}

mark_step_complete() {
    local step_number=$1
    local step_name=$2

    LAST_COMPLETED_STEP=$step_number

    case $step_number in
        1) STEP_1_VERIFY_PREREQUISITES="completed" ;;
        2) STEP_2_INSTALL_PACKAGES="completed" ;;
        3) STEP_3_CONFIGURE_UFW="completed" ;;
    esac

    show_success "Completed: Step $step_number ($step_name)"
    save_state
}

# ==============================================================================
# Trap Handlers
# ==============================================================================
cleanup_on_exit() {
    local exit_code=$?

    if [[ "$CLEANUP_CALLED" == true ]]; then
        return
    fi
    CLEANUP_CALLED=true

    if [[ $exit_code -ne 0 ]]; then
        echo "" >&3
        show_warning "Script interrupted or exiting with code $exit_code"

        if [[ -c /dev/tty ]]; then
            echo "" >&3
            echo -n "Save current state before exiting? (yes/no): " >&3
            read -r save_choice < /dev/tty 2>&3 || save_choice=""
            if [[ "$save_choice" == "yes" ]]; then
                save_state
                show_success "State saved. Next run will allow resume."
            fi
        fi
    fi

    rm -f "${STATE_FILE}.tmp" "${CREDS_FILE}.tmp"
}

trap 'cleanup_on_exit' EXIT INT TERM

# ==============================================================================
# Pre-flight Validation
# ==============================================================================
check_prerequisites() {
    local validation_failed=false

    show_info "Validating prerequisites..."

    # Ubuntu version check
    if [[ -f /etc/os-release ]]; then
        # shellcheck disable=SC1091
        source /etc/os-release
        if [[ "$PRETTY_NAME" != "Ubuntu 24.04"* ]]; then
            show_error "This script requires Ubuntu 24.04. Detected: $PRETTY_NAME. Aborting."
            validation_failed=true
        else
            show_success "Ubuntu version: $PRETTY_NAME"
        fi
    else
        show_error "Cannot determine OS version (/etc/os-release not found)."
        validation_failed=true
    fi

    # Required binaries check
    local required_binaries=("sudo" "curl" "apt-get")
    for binary in "${required_binaries[@]}"; do
        if command -v "$binary" &>/dev/null; then
            show_success "Binary found: $binary"
        else
            show_error "Missing required binary: $binary. Install with: sudo apt-get install $binary"
            validation_failed=true
        fi
    done

    # Disk space validation
    local available_disk_gb
    available_disk_gb=$(df -BG / | tail -1 | awk '{print $4}' | sed 's/G//')
    if [[ $available_disk_gb -lt 10 ]]; then
        show_error "Insufficient disk space. Available: ${available_disk_gb}GB, Minimum required: 10GB"
        validation_failed=true
    elif [[ $available_disk_gb -lt 20 ]]; then
        show_warning "Low disk space. Available: ${available_disk_gb}GB (recommended minimum: 20GB)"
    else
        show_success "Disk space: ${available_disk_gb}GB available (≥20GB)"
    fi

    # Root check
    if [[ $UID -ne 0 ]]; then
        show_error "This script must be run as root. Run with: sudo bash install-deps.sh"
        validation_failed=true
    fi

    if [[ "$validation_failed" == true ]]; then
        return 1
    fi
    return 0
}

# ==============================================================================
# Step Implementations
# ==============================================================================
ensure_file_permissions() {
    # Ensure state and log files are readable/writable by the original user
    # This is critical for transitioning from root (install-deps.sh) to non-root (deploy.sh)
    local original_user="${SUDO_USER:-root}"

    if [[ -f "$STATE_FILE" ]]; then
        chmod 644 "$STATE_FILE"
        if [[ "$original_user" != "root" ]]; then
            chown "$original_user:$original_user" "$STATE_FILE" 2>/dev/null || true
        fi
    fi

    if [[ -f "$CREDS_FILE" ]]; then
        chmod 600 "$CREDS_FILE"
        if [[ "$original_user" != "root" ]]; then
            chown "$original_user:$original_user" "$CREDS_FILE" 2>/dev/null || true
        fi
    fi

    if [[ -f "$LOG_FILE" ]]; then
        chmod 644 "$LOG_FILE"
        if [[ "$original_user" != "root" ]]; then
            chown "$original_user:$original_user" "$LOG_FILE" 2>/dev/null || true
        fi
    fi
}

install_terraform_manual() {
    local tf_version="1.15.3"
    local tf_zip="terraform_${tf_version}_linux_amd64.zip"
    local tf_url="https://releases.hashicorp.com/terraform/${tf_version}/${tf_zip}"
    local tf_tmp="/tmp/${tf_zip}"

    show_info "Installing unzip..."
    echo "[$(get_timestamp)] Running: apt-get install -y unzip" >> "$LOG_FILE"
    if ! apt-get install -y unzip >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to install unzip" >> "$LOG_FILE"
        error_exit "Failed to install unzip (required for manual Terraform installation)" "apt"
    fi

    show_info "Downloading Terraform ${tf_version} from releases.hashicorp.com..."
    echo "[$(get_timestamp)] Downloading: $tf_url" >> "$LOG_FILE"
    if ! curl -fsSL "$tf_url" -o "$tf_tmp" >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to download Terraform zip from $tf_url" >> "$LOG_FILE"
        error_exit "Failed to download Terraform ${tf_version} — check network connectivity"
    fi

    show_info "Extracting Terraform binary..."
    echo "[$(get_timestamp)] Running: unzip $tf_tmp -d /tmp" >> "$LOG_FILE"
    if ! unzip -o "$tf_tmp" terraform -d /tmp >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: unzip failed for $tf_tmp" >> "$LOG_FILE"
        error_exit "Failed to extract Terraform zip"
    fi

    show_info "Installing Terraform to /usr/local/bin/..."
    echo "[$(get_timestamp)] Running: mv /tmp/terraform /usr/local/bin/" >> "$LOG_FILE"
    if ! sudo mv /tmp/terraform /usr/local/bin/ >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to move terraform binary to /usr/local/bin/" >> "$LOG_FILE"
        error_exit "Failed to install Terraform binary"
    fi
    chmod +x /usr/local/bin/terraform

    rm -f "$tf_tmp"

    if terraform --version >/dev/null 2>&1; then
        show_success "Terraform $(terraform --version | head -1 | awk '{print $2}') installed (manual)"
        echo "[$(get_timestamp)] Manual Terraform installation succeeded: $(terraform --version | head -1)" >> "$LOG_FILE"
    else
        echo "[$(get_timestamp)] ERROR: Terraform binary not functional after manual installation" >> "$LOG_FILE"
        show_error "Terraform installation did not work — binary not found in PATH after manual install"
        error_exit "Manual Terraform installation failed"
    fi
}

step_install_packages() {
    show_info "⏳ Configuring package repositories..."
    echo "[$(get_timestamp)] Starting package installation" >> "$LOG_FILE"

    # Initial setup
    show_info "Installing prerequisite packages (gnupg, software-properties-common, ca-certificates)..."
    echo "[$(get_timestamp)] Running: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common ca-certificates" >> "$LOG_FILE"

    if ! apt-get update >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: apt-get update failed" >> "$LOG_FILE"
        error_exit "apt-get update failed" "apt"
    fi

    if ! apt-get install -y gnupg software-properties-common ca-certificates >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: prerequisite package installation failed" >> "$LOG_FILE"
        error_exit "Failed to install prerequisite packages" "apt"
    fi
    show_success "Prerequisite packages installed"

    # Add HashiCorp Repository for Terraform with retry logic
    local hashicorp_setup_success=false
    local retry_count=0
    local max_retries=3

    # Consistent codename detection (matching Docker setup)
    local ubuntu_codename
    ubuntu_codename=$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    
    # Fallback for non-standard environments
    if [[ -z "$ubuntu_codename" ]]; then
        if command -v lsb_release >/dev/null 2>&1; then
            ubuntu_codename=$(lsb_release -cs)
        fi
    fi
    
    if [[ -z "$ubuntu_codename" ]]; then
        echo "[$(get_timestamp)] WARNING: Could not determine Ubuntu codename, defaulting to 'noble'" >> "$LOG_FILE"
        ubuntu_codename="noble"
    fi

    # Architecture detection
    local arch
    arch=$(dpkg --print-architecture)

    while [[ $retry_count -lt $max_retries ]] && [[ "$hashicorp_setup_success" == false ]]; do
        retry_count=$((retry_count + 1))

        if [[ ! -f /etc/apt/keyrings/hashicorp-archive-keyring.gpg ]]; then
            show_info "⏳ Setting up HashiCorp repository (attempt $retry_count/$max_retries)..."
            echo "[$(get_timestamp)] HashiCorp setup attempt $retry_count/$max_retries" >> "$LOG_FILE"

            local curl_error_file=$(mktemp)
            local gpg_error_file=$(mktemp)

            if ! mkdir -p /etc/apt/keyrings >> "$LOG_FILE" 2>&1; then
                echo "[$(get_timestamp)] ERROR: Failed to create /etc/apt/keyrings" >> "$LOG_FILE"
            fi

            echo "[$(get_timestamp)] Downloading HashiCorp GPG key from https://apt.releases.hashicorp.com/gpg" >> "$LOG_FILE"

            if curl -fsSL https://apt.releases.hashicorp.com/gpg 2>"$curl_error_file" | \
               gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg 2>"$gpg_error_file"; then

                echo "[$(get_timestamp)] Curl/GPG key creation succeeded" >> "$LOG_FILE"

                if [[ -f /etc/apt/keyrings/hashicorp-archive-keyring.gpg ]]; then
                    echo "[$(get_timestamp)] GPG keyring file verified: /etc/apt/keyrings/hashicorp-archive-keyring.gpg" >> "$LOG_FILE"
                    chmod a+r /etc/apt/keyrings/hashicorp-archive-keyring.gpg

                    echo "[$(get_timestamp)] Adding HashiCorp repository for codename: $ubuntu_codename ($arch)" >> "$LOG_FILE"

                    if echo "deb [arch=$arch signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $ubuntu_codename main" | \
                       tee /etc/apt/sources.list.d/hashicorp.list >/dev/null; then

                        if [[ -f /etc/apt/sources.list.d/hashicorp.list ]]; then
                            echo "[$(get_timestamp)] HashiCorp sources list file created successfully" >> "$LOG_FILE"
                            hashicorp_setup_success=true
                            show_success "HashiCorp repository configured successfully"
                        else
                            echo "[$(get_timestamp)] ERROR: HashiCorp sources list file was not created" >> "$LOG_FILE"
                        fi
                    else
                        echo "[$(get_timestamp)] ERROR: Failed to write HashiCorp sources list" >> "$LOG_FILE"
                    fi
                else
                    echo "[$(get_timestamp)] ERROR: HashiCorp GPG keyring was not created despite successful curl/gpg" >> "$LOG_FILE"
                fi
            else
                local curl_error=$(cat "$curl_error_file" 2>/dev/null || echo "unknown error")
                local gpg_error=$(cat "$gpg_error_file" 2>/dev/null || echo "unknown error")

                echo "[$(get_timestamp)] ERROR: Curl/GPG failed. Curl: $curl_error | GPG: $gpg_error" >> "$LOG_FILE"

                if [[ $retry_count -lt $max_retries ]]; then
                    local backoff_delay=$((2 ** (retry_count - 1)))
                    show_warning "HashiCorp repo setup failed. Retrying in ${backoff_delay}s..."
                    sleep "$backoff_delay"
                else
                    echo "[$(get_timestamp)] ERROR: HashiCorp repository setup failed after $max_retries attempts" >> "$LOG_FILE"
                    show_warning "HashiCorp repository setup failed after $max_retries attempts"
                    show_warning "Will attempt to install packages without Terraform"
                fi
            fi

            rm -f "$curl_error_file" "$gpg_error_file"
        else
            show_info "⏳ HashiCorp GPG key already exists, ensuring sources list is correct..."
            echo "[$(get_timestamp)] GPG keyring already exists, configuring sources list for $ubuntu_codename ($arch)..." >> "$LOG_FILE"

            if echo "deb [arch=$arch signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $ubuntu_codename main" | \
               tee /etc/apt/sources.list.d/hashicorp.list >/dev/null && \
               [[ -f /etc/apt/sources.list.d/hashicorp.list ]]; then
                echo "[$(get_timestamp)] HashiCorp sources list configured successfully" >> "$LOG_FILE"
                hashicorp_setup_success=true
                show_success "HashiCorp repository sources list configured"
            else
                echo "[$(get_timestamp)] ERROR: Failed to configure HashiCorp repository sources list" >> "$LOG_FILE"
                show_warning "Failed to configure HashiCorp repository sources list"
            fi
        fi
    done

    # Install Docker using official method
    show_info "Setting up Docker from official repository..."
    echo "[$(get_timestamp)] Installing Docker prerequisites and official repository" >> "$LOG_FILE"

    if ! apt-get install -y ca-certificates curl >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to install prerequisites" >> "$LOG_FILE"
        error_exit "Failed to install Docker prerequisites" "apt"
    fi

    if ! install -m 0755 -d /etc/apt/keyrings >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to create keyrings directory" >> "$LOG_FILE"
        error_exit "Failed to set up Docker GPG key directory" "apt"
    fi

    if ! curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to download Docker GPG key" >> "$LOG_FILE"
        error_exit "Failed to download Docker GPG key" "apt"
    fi

    if ! chmod a+r /etc/apt/keyrings/docker.asc >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to set Docker GPG key permissions" >> "$LOG_FILE"
        error_exit "Failed to set Docker GPG key permissions" "apt"
    fi

    local ubuntu_codename
    ubuntu_codename=$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    local arch
    arch=$(dpkg --print-architecture)

    if ! tee /etc/apt/sources.list.d/docker.sources <<EOF >> "$LOG_FILE" 2>&1
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $ubuntu_codename
Components: stable
Architectures: $arch
Signed-By: /etc/apt/keyrings/docker.asc
EOF
    then
        echo "[$(get_timestamp)] ERROR: Failed to configure Docker repository" >> "$LOG_FILE"
        error_exit "Failed to configure Docker repository" "apt"
    fi
    show_success "Docker repository configured"

    # Update package lists
    show_info "Updating package lists..."
    echo "[$(get_timestamp)] Running: apt-get clean && rm -rf /var/lib/apt/lists/* && apt-get update" >> "$LOG_FILE"

    apt-get clean >> "$LOG_FILE" 2>&1
    # Deep clean lists to force a full refresh
    rm -rf /var/lib/apt/lists/* >> "$LOG_FILE" 2>&1
    
    if ! apt-get update >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: apt-get update failed after repository configuration" >> "$LOG_FILE"
        error_exit "Failed to update package lists. Check $LOG_FILE for details." "apt"
    fi
    show_success "Package lists updated"

    # Diagnostic: Check if terraform is available
    if [[ "$hashicorp_setup_success" == true ]]; then
        echo "[$(get_timestamp)] Diagnostic: Checking if terraform is available in apt cache..." >> "$LOG_FILE"
        if [[ -f /etc/apt/sources.list.d/hashicorp.list ]]; then
            echo "[$(get_timestamp)] HashiCorp list content: $(cat /etc/apt/sources.list.d/hashicorp.list)" >> "$LOG_FILE"
        fi

        # We separate declaration and assignment to capture exit code correctly if needed
        local policy_out
        policy_out=$(apt-cache policy terraform 2>&1) || policy_out="apt-cache command failed"
        
        echo "--- apt-cache policy terraform output ---" >> "$LOG_FILE"
        echo "$policy_out" >> "$LOG_FILE"
        echo "-----------------------------------------" >> "$LOG_FILE"

        if echo "$policy_out" | grep -q "Candidate: (none)"; then
             echo "[$(get_timestamp)] WARNING: Terraform has no installation candidate in apt cache" >> "$LOG_FILE"
             hashicorp_setup_success=false
        elif ! echo "$policy_out" | grep -q "Candidate:"; then
             echo "[$(get_timestamp)] WARNING: Could not find Candidate info in apt-cache output" >> "$LOG_FILE"
             hashicorp_setup_success=false
        else
             local candidate
             candidate=$(echo "$policy_out" | grep "Candidate:" | awk '{print $2}')
             echo "[$(get_timestamp)] Terraform candidate found: $candidate" >> "$LOG_FILE"
        fi
    fi

    # Install Docker, Git, and other packages
    if [[ "$hashicorp_setup_success" == true ]]; then
        show_info "Installing packages: Docker, Git, Terraform 1.12.1, jq..."
        echo "[$(get_timestamp)] Running: apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git terraform=1.12.1-1 jq" >> "$LOG_FILE"

        if ! apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git terraform=1.12.1-1 jq >> "$LOG_FILE" 2>&1; then
            echo "[$(get_timestamp)] ERROR: Package installation failed" >> "$LOG_FILE"
            tail -20 "$LOG_FILE" | grep -i error || true
            error_exit "Package installation failed (see $LOG_FILE for details)" "apt"
        fi
    else
        show_warning "Skipping Terraform installation (HashiCorp repository unavailable)"
        show_info "Installing packages: Docker, Git, jq..."
        echo "[$(get_timestamp)] Running: apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git jq (Terraform skipped)" >> "$LOG_FILE"

        if ! apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git jq >> "$LOG_FILE" 2>&1; then
            echo "[$(get_timestamp)] ERROR: Package installation failed (without Terraform)" >> "$LOG_FILE"
            error_exit "Package installation failed (see $LOG_FILE for details)" "apt"
        fi
    fi
    show_success "Packages installed"

    # Verify and show versions
    echo "[$(get_timestamp)] Verifying installed packages..." >> "$LOG_FILE"

    docker --version >/dev/null 2>&1 || error_exit "Docker not found after installation" "apt"
    show_success "Docker $(docker --version | awk '{print $3}' | tr -d ',') installed"
    echo "[$(get_timestamp)] Docker $(docker --version)" >> "$LOG_FILE"

    docker compose version >/dev/null 2>&1 || error_exit "Docker Compose not found after installation" "apt"
    show_success "Docker Compose $(docker compose version | awk '{print $4}')"
    echo "[$(get_timestamp)] Docker Compose $(docker compose version)" >> "$LOG_FILE"

    # Add deployment user to docker group for passwordless execution
    local deploy_user="${SUDO_USER:-root}"
    show_info "Adding $deploy_user to docker group..."
    echo "[$(get_timestamp)] Adding $deploy_user to docker group" >> "$LOG_FILE"
    if ! usermod -aG docker "$deploy_user" >> "$LOG_FILE" 2>&1; then
        echo "[$(get_timestamp)] ERROR: Failed to add $deploy_user to docker group" >> "$LOG_FILE"
        error_exit "Failed to add user to docker group" "docker"
    else
        echo "[$(get_timestamp)] Successfully added $deploy_user to docker group" >> "$LOG_FILE"
        show_success "$deploy_user added to docker group"
    fi

    git --version >/dev/null 2>&1 || error_exit "Git not found after installation" "apt"
    show_success "Git $(git --version | awk '{print $3}') installed"
    echo "[$(get_timestamp)] Git $(git --version)" >> "$LOG_FILE"

    jq --version >/dev/null 2>&1 || error_exit "jq not found after installation" "apt"
    show_success "jq $(jq --version | head -1) installed"
    echo "[$(get_timestamp)] jq $(jq --version)" >> "$LOG_FILE"

    if terraform --version >/dev/null 2>&1; then
        show_success "Terraform $(terraform --version | head -1 | awk '{print $2}') installed"
        echo "[$(get_timestamp)] Terraform $(terraform --version | head -1)" >> "$LOG_FILE"
    else
        if [[ "$hashicorp_setup_success" == true ]]; then
            echo "[$(get_timestamp)] ERROR: Terraform not found despite successful repo setup" >> "$LOG_FILE"
            error_exit "Terraform not found despite successful repo setup" "apt"
        else
            show_warning "HashiCorp APT repository unavailable — attempting manual Terraform installation..."
            echo "[$(get_timestamp)] Falling back to manual Terraform installation from releases.hashicorp.com" >> "$LOG_FILE"
            install_terraform_manual
        fi
    fi

    echo "[$(get_timestamp)] Package installation step completed successfully" >> "$LOG_FILE"
    mark_step_complete 2 "Install Packages"

    echo ""
    show_header "⏸️  PAUSING INSTALLATION - ACTION REQUIRED"
    echo ""
    show_info "Docker group membership requires you to log out and log back in."
    show_info "After that, the non-root steps can proceed."
    echo ""
    show_info "Steps:"
    show_info "  1. Exit this SSH session: type 'exit' or close the connection"
    show_info "  2. SSH back in"
    show_info "  3. Run: bash deploy.sh"
    echo ""
    show_warning "⚠️  IMPORTANT: Run deploy.sh WITHOUT sudo."
    show_warning "    Run as: bash deploy.sh (NOT: sudo bash deploy.sh)"
    echo ""
    show_info "To verify Docker access after login: docker ps"
    echo ""
    echo "[$(get_timestamp)] Step 2 paused - user must log out and back in" >> "$LOG_FILE"

    # Ensure non-root user can access state and log files
    ensure_file_permissions
    exit 0
}

step_configure_ufw() {
    show_info "Checking UFW status..."

    if ufw status | grep -q "Status: active"; then
        show_info "UFW firewall already enabled."
        mark_step_complete 3 "Configure UFW"
        return 0
    fi

    show_warning "Firewall Configuration"
    echo "" >&3
    echo "UFW will be enabled with these rules:" >&3
    echo "  • Incoming: Deny (default)" >&3
    echo "  • Outgoing: Allow (default)" >&3
    echo "  • SSH (port 22): Allow" >&3
    echo "  • HTTP (port 80): Allow" >&3
    echo "  • HTTPS (port 443): Allow" >&3
    echo "" >&3
    echo -n "$(get_timestamp) ${BLUE}⏳ SSH access will remain available. Continue? (y/n): ${NC}" >&3
    read -r ufw_choice < /dev/tty 2>&3 || ufw_choice=""

    if [[ "$ufw_choice" == "y" ]]; then
        show_info "Applying UFW rules..."
        echo "[$(get_timestamp)] Configuring UFW firewall rules..." >> "$LOG_FILE"

        ufw default deny incoming >> "$LOG_FILE" 2>&1
        ufw allow 22/tcp >> "$LOG_FILE" 2>&1
        ufw allow 80/tcp >> "$LOG_FILE" 2>&1
        ufw allow 443/tcp >> "$LOG_FILE" 2>&1

        if ufw --force enable >> "$LOG_FILE" 2>&1; then
            show_success "UFW firewall configured and enabled."
            echo "[$(get_timestamp)] UFW firewall enabled successfully" >> "$LOG_FILE"
            ufw status >&3
        else
            show_warning "UFW enable command failed, but rules may be applied"
            echo "[$(get_timestamp)] WARNING: UFW enable had issues but continuing" >> "$LOG_FILE"
        fi
    else
        show_warning "Skipping UFW configuration."
        echo "[$(get_timestamp)] User skipped UFW configuration" >> "$LOG_FILE"
    fi

    mark_step_complete 3 "Configure UFW"
    return 0
}

# ==============================================================================
# Usage and Help
# ==============================================================================
usage() {
    cat <<EOF
GoalDone Dependency Installation Script

Usage:
  sudo bash install-deps.sh [OPTIONS]

Options:
  --help                Show this help message

Prerequisites:
  - Run with sudo
  - Ubuntu 24.04
  - Network access

Description:
  This script installs system packages and dependencies requiring sudo:
  - Docker and Docker Compose
  - Git
  - Terraform
  - UFW firewall configuration

After this completes, run: bash deploy.sh (without sudo)
EOF
}

# ==============================================================================
# Argument Parsing
# ==============================================================================
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)
            usage
            exit 0
            ;;
        *)
            show_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

# ==============================================================================
# Main Execution
# ==============================================================================
load_state

if [[ $UID -ne 0 ]]; then
    show_error "This script must be run as root. Run with: sudo bash install-deps.sh"
    exit 1
fi

main() {
    # Initialize logging
    exec >> "$LOG_FILE" 2>&1

    show_header "GoalDone Dependency Installation"
    show_info "Starting dependency installation"

    # Step 1: Pre-flight validation
    if ! check_prerequisites; then
        show_error "Pre-flight validation failed. See $LOG_FILE for details."
        exit 1
    fi
    show_success "All prerequisites met."
    mark_step_complete 1 "Verify Prerequisites"

    show_info "Starting execution from Step 2 to Step $TOTAL_STEPS..."
    echo "" >&3

    # Step 2: Install Packages
    show_header "Step 2: Install Packages"
    step_install_packages

    # Step 3: Configure UFW (only if we reach here after install-packages pause)
    show_header "Step 3: Configure UFW"
    step_configure_ufw

    show_header "Installation Complete"
    show_success "All dependency installation steps completed!"
    show_info "Now run: bash deploy.sh"

    # Ensure non-root user can access state and log files
    ensure_file_permissions
}

main
