spring:
  application:
    name: backend
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:https://sso.dev.goaldone.de}
      client:
        registration:
          auth-service-mgmt:
            client-id: ${MGMT_CLIENT_ID:mgmt-client}
            client-secret: ${MGMT_CLIENT_SECRET:mgmt-secret}
            authorization-grant-type: client_credentials
            scope: mgmt:admin
        provider:
          auth-service-mgmt:
            token-uri: ${AUTH_SERVICE_URL:http://localhost:9000}/oauth2/token

auth-service:
  base-url: ${AUTH_SERVICE_URL:http://localhost:9000}

server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
