spring:
  datasource:
    url: jdbc:h2:mem:goaldonedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: TRACE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ZITADEL_ISSUER_URI:http://localhost:8080}