spring:
  application:
    name: backend
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ZITADEL_ISSUER_URI:http://localhost:8080}

zitadel:
  service-account-token: ${ZITADEL_SERVICE_ACCOUNT_TOKEN:}
  goaldone:
    project-id: ${ZITADEL_GOALDONE_PROJECT_ID:}

server:
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
